[package]
name = "rocket-test"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"

